name: Mirror snapshots

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: mirror missing assets
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          set -x

          gh api --paginate repos/git-for-windows/git-snapshots/releases \
            --jq '.[].assets[].browser_download_url' >all-urls.txt &&

          comm -23 \
            <(tr '"' '\n' <index.html | grep ^https://github.com/git-for-windows/git-snapshots/releases | sort) \
            <(sort <all-urls.txt) \
            >missing.txt

          while read url
          do
            file=${url##*/}
            tag=${url%/*}
            tag=${tag##*/}

            curl -fLo "$file" https://wingit.blob.core.windows.net/files/"$file" &&
            gh release upload -R ${{ github.repository }} "$tag" "$file" || exit 1
          done <missing.txt
